### ISSUE TITLE
Man Hello

### ISSUE THREAD

**Issue by xxkvl** [AndreyKorol/profitero-script#2]
Привет, Андрей, нашей компании хотелось бы предложить вам должность Junior Ruby Developer, как вы относитесь к этому?

**Comment by AndreyKorol** [comment]
Hello, Dimon!

![photo5438534224853445594](https://user-images.githubusercontent.com/24570463/64454053-9f03cc00-d0f2-11e9-91b7-56102873bea3.jpg)

**Comment by xxkvl** [comment]
😄
